apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paperless
  name: paperless
  namespace: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
        - image: ghcr.io/paperless-ngx/paperless-ngx:2.16.2
          name: paperless-ngx
          ports:
            - containerPort: 8000
          env:
            - name: PAPERLESS_REDIS
              value: redis://localhost:6379
        - image: redis:7
          name: redis
          ports:
            - containerPort: 6379
